project-management-tool/config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# get('/', to: 'welcome#home')
# get('/projects/', to: 'projects#index')
# get('/projects/:id', {to: 'projects#show', as: :project})
get('/tasks/', to: 'tasks#index')
get('/discussions/', to: 'discussions#index')
get('/comments/', to: 'comments#index')
#
# get('/projects/new/', {to: 'projects#new', as: :new_project})
# post('/projects', to: 'projects#create')

resources :projects do
  resources :favourites, only: [:create, :destroy]
end
# get('/projects/:id/edit', {to: 'projects#edit', as: :edit_project})
# patch('/projects/:id', {to: 'projects#update'})
# delete('/projects/:id', {to: 'projects#destroy'})
end

project-management-tool/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def pretty_errors
    self.errors.full_messages.join(', ')
  end
end

project-management-tool/app/models/comment.rb
class Comment < ApplicationRecord
      validates(:body, presence: {message: 'must be provided'})
end

project-management-tool/app/models/discussion.rb
class Discussion < ApplicationRecord
    validates(:title, presence: {message: 'must be provided'})
end

project-management-tool/app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates :project_id, uniqueness: { scope: :user_id}
end

project-management-tool/app/models/project.rb
class Project < ApplicationRecord

  has_many :favourites, dependent: :destroy
  has_many :favers, through: :favourites, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates(:title, presence: {message: 'must be provided'}, uniqueness: true)
end

project-management-tool/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :projects, through: :taggings

  validates :name, presence: true, uniqueness: true
end

project-management-tool/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :project
end

project-management-tool/app/models/task.rb
class Task < ApplicationRecord
    validates(:title, presence: {message: 'must be provided'}, uniqueness: true)  
end

project-management-tool/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :favourites, dependent: :destroy
  has_many :favourited_projects, through: :favourites, source: :project

  validates_uniqueness_of :email
end

project-management-tool/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

project-management-tool/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to projects_path, notice: 'Thanks for signing in!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation])
  end
end

project-management-tool/app/helpers/application_helper.rb
module ApplicationHelper
end

project-management-tool/app/helpers/comments_helper.rb
module CommentsHelper
end

project-management-tool/app/helpers/discussions_helper.rb
module DiscussionsHelper
end

project-management-tool/app/helpers/favourites_helper.rb
module FavouritesHelper
end

project-management-tool/app/helpers/projects_helper.rb
module ProjectsHelper
end

project-management-tool/app/helpers/sessions_helper.rb
module SessionsHelper
end

project-management-tool/app/helpers/tasks_helper.rb
module TasksHelper
end

project-management-tool/app/helpers/users_helper.rb
module UsersHelper
end

project-management-tool/app/helpers/welcome_helper.rb
module WelcomeHelper
end

project-management-tool/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagementTool</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
        <%= link_to('Home', '/') %>
        |
        <%= link_to('Projects', projects_path) %>
        |
        <%= link_to('Tasks', tasks_path) %>
        |
        <%= link_to('Discussions', discussions_path) %>
        |
        <%#= link_to('Create new product', products_new_path) %>
        <%= link_to('Create new project', new_project_path) %>

        <% if current_user.present? %>
          Welcome <%= current_user.first_name %>
          <%= link_to 'Log Out', logout_path, method: :delete %>

        <% else %>
          <%= link_to 'Sign up', signup_path %>
          |
          <%= link_to 'Log In', login_path %>
        <% end %>

        <% if flash.any? %>
         <hr>
         <% if flash[:notice] %>
           <div class="flash-notice"><%= flash[:notice] %></div>
         <% elsif flash[:alert] %>
           <div class="flash-alert"><%= flash[:alert] %></div>
         <% end %>
         <hr>
        <% end %>
    <%= yield %>
  </body>
</html>