project-management-tool/config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# get('/', to: 'welcome#home')
# get('/projects/', to: 'projects#index')
# get('/projects/:id', {to: 'projects#show', as: :project})
get('/tasks/', to: 'tasks#index')
get('/discussions/', to: 'discussions#index')
get('/comments/', to: 'comments#index')
#
# get('/projects/new/', {to: 'projects#new', as: :new_project})
# post('/projects', to: 'projects#create')

resources :projects do
  resources :favourites, only: [:create, :destroy]
end
# get('/projects/:id/edit', {to: 'projects#edit', as: :edit_project})
# patch('/projects/:id', {to: 'projects#update'})
# delete('/projects/:id', {to: 'projects#destroy'})
end

project-management-tool/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def pretty_errors
    self.errors.full_messages.join(', ')
  end
end

project-management-tool/app/models/comment.rb
class Comment < ApplicationRecord
      validates(:body, presence: {message: 'must be provided'})
end

project-management-tool/app/models/discussion.rb
class Discussion < ApplicationRecord
    validates(:title, presence: {message: 'must be provided'})
end

project-management-tool/app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates :project_id, uniqueness: { scope: :user_id}
end

project-management-tool/app/models/project.rb
class Project < ApplicationRecord

  has_many :favourites, dependent: :destroy
  has_many :favers, through: :favourites, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates(:title, presence: {message: 'must be provided'}, uniqueness: true)
end

project-management-tool/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :projects, through: :taggings

  validates :name, presence: true, uniqueness: true
end

project-management-tool/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :project
end

project-management-tool/app/models/task.rb
class Task < ApplicationRecord
    validates(:title, presence: {message: 'must be provided'}, uniqueness: true)  
end

project-management-tool/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :favourites, dependent: :destroy
  has_many :favourited_projects, through: :favourites, source: :project

  validates_uniqueness_of :email
end

project-management-tool/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end
end

project-management-tool/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorize!, except: [:index, :show]

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path(@project), notice: "Succesfully Created"
    else
      flash.now[:alert] = "Unable to Created"
      render :new
    end
  end

  def show
  @project = Project.find params[:id]
  # render json: params
  end
  def index
    @projects = Project.all
  end

  def destroy
    @project = Project.find params[:id]
    @project.destroy
    redirect_to projects_path "Project Deleted"
  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    @project = Project.find params[:id]

    if @project.update(project_params)
      redirect_to project_path(@project), notice: "Succesfully Updated"
    else
      flash.now[:alert] = "Unable to Updated"
      render :edit
    end
  end

  private
  
  def project_params
    params.require(:project).permit([:title, :description, { tag_ids: [] }])
  end
end

project-management-tool/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

project-management-tool/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to projects_path, notice: 'Thanks for signing in!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation])
  end
end

project-management-tool/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

project-management-tool/app/helpers/application_helper.rb
module ApplicationHelper
end

project-management-tool/app/helpers/comments_helper.rb
module CommentsHelper
end

project-management-tool/app/helpers/discussions_helper.rb
module DiscussionsHelper
end

project-management-tool/app/helpers/favourites_helper.rb
module FavouritesHelper
end

project-management-tool/app/helpers/projects_helper.rb
module ProjectsHelper
end

project-management-tool/app/helpers/sessions_helper.rb
module SessionsHelper
end

project-management-tool/app/helpers/tasks_helper.rb
module TasksHelper
end

project-management-tool/app/helpers/users_helper.rb
module UsersHelper
end

project-management-tool/app/helpers/welcome_helper.rb
module WelcomeHelper
end

project-management-tool/app/views/comments/index.html.erb
<h1>Comments</h1>

project-management-tool/app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <% @project.errors.full_messages.each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<%= form_for @project do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-control">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :tag_ids %>
    <%= f.collection_select :tag_ids, Tag.all, :id, :name,
     {}, { multiple: true, class: 'chosen-select'} %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

project-management-tool/app/views/projects/edit.html.erb
<h1>Edit Products</h1>


<%= render 'form' %>

project-management-tool/app/views/projects/index.html.erb
<h1>Projects</h1>


<h1>All Projects</h1>
<% @projects.each do |project| %>
<%= link_to project.title, project_path(project) %>
<hr>
<% end %>

project-management-tool/app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

project-management-tool/app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<p><%= @project.description %></p>
<p>Tags: <%= @project.tags.map(&:name).join(', ') %></p>

<% favourite = @project.favourites.find_by(user: current_user) %>
<% if favourite  %>
  <%= link_to '👎', project_favourite_path(@project, favourite), method: :delete %>
<% else %>
  <%= link_to '👍', project_favourites_path(@project), method: :post %>
<% end %>

(<%= pluralize @project.favourites.count, 'favourite' %>)

<%= link_to 'Edit', edit_project_path(@project) %>
<%= link_to('Delete', project_path(@project),
                      method: :delete,
                      data: {confirm: 'Are you sure?'}) %>

project-management-tool/app/views/tasks/index.html.erb
<h1>Tasks</h1>

project-management-tool/app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="action"><%= f.submit %></div>
 <% end %>